//! JSON Schema generation for Bivvy configuration.
//!
//! The schema is generated from Rust config types via `schemars` at build time
//! and embedded into the binary. At runtime, [`embedded_schema_json`] returns
//! the pre-built JSON string — no computation required.
//!
//! [`SchemaGenerator`] remains available for regenerating the schema (used by
//! the release script and freshness tests).

use serde_json::Value;

use crate::config::schema::BivvyConfig;

/// Pre-built JSON Schema embedded at compile time.
///
/// This file is regenerated by `scripts/release.sh` before each tagged release,
/// so the schema shipped in the binary always matches that version's config types.
pub const EMBEDDED_SCHEMA_JSON: &str = include_str!("../../generated/schema.json");

/// Returns the embedded JSON Schema as a parsed [`Value`].
pub fn embedded_schema() -> Value {
    serde_json::from_str(EMBEDDED_SCHEMA_JSON).expect("embedded schema is valid JSON")
}

/// Generates JSON Schema for Bivvy configuration at runtime.
///
/// Used by `scripts/generate-schema.sh` to regenerate `generated/schema.json`
/// and by tests to verify the embedded schema stays in sync with the config types.
pub struct SchemaGenerator;

impl SchemaGenerator {
    /// Create a new schema generator.
    pub fn new() -> Self {
        Self
    }

    /// Generate the complete JSON Schema for bivvy.yml.
    ///
    /// Uses `schemars` to derive the schema from the Rust type definitions,
    /// ensuring the schema always matches the actual config parser.
    pub fn generate(&self) -> Value {
        let settings = schemars::gen::SchemaSettings::draft07().with(|s| {
            s.option_nullable = false;
            s.option_add_null_type = true;
        });
        let gen = settings.into_generator();
        let schema = gen.into_root_schema_for::<BivvyConfig>();
        let mut value = serde_json::to_value(schema).expect("schema serializes to JSON");

        // Inject the canonical $id for remote reference.
        if let Some(obj) = value.as_object_mut() {
            obj.insert(
                "$id".to_string(),
                Value::String("https://bivvy.dev/schemas/config.json".to_string()),
            );
        }

        value
    }
}

impl Default for SchemaGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_valid_json_schema() {
        let generator = SchemaGenerator::new();
        let schema = generator.generate();

        assert_eq!(schema["$schema"], "http://json-schema.org/draft-07/schema#");
        assert_eq!(schema["type"], "object");
    }

    #[test]
    fn includes_canonical_id() {
        let generator = SchemaGenerator::new();
        let schema = generator.generate();

        assert_eq!(schema["$id"], "https://bivvy.dev/schemas/config.json");
    }

    #[test]
    fn includes_all_top_level_properties() {
        let generator = SchemaGenerator::new();
        let schema = generator.generate();

        let props = schema["properties"].as_object().expect("has properties");
        for key in &[
            "app_name",
            "settings",
            "template_sources",
            "steps",
            "workflows",
            "secrets",
            "extends",
            "requirements",
            "vars",
        ] {
            assert!(
                props.contains_key(*key),
                "missing top-level property: {key}"
            );
        }
    }

    #[test]
    fn steps_uses_additional_properties() {
        let generator = SchemaGenerator::new();
        let schema = generator.generate();

        let steps = &schema["properties"]["steps"];
        // Steps is a HashMap<String, StepConfig>, so schemars generates
        // additionalProperties pointing to the StepConfig schema.
        assert!(
            steps.get("additionalProperties").is_some()
                || steps.get("$ref").is_some()
                || steps["type"] == "object",
            "steps should be an object type"
        );
    }

    #[test]
    fn var_definition_generates_any_of() {
        let generator = SchemaGenerator::new();
        let schema = generator.generate();

        // VarDefinition is untagged enum, so schemars generates anyOf
        let schema_str = serde_json::to_string(&schema).unwrap();
        assert!(
            schema_str.contains("VarDefinition"),
            "schema should reference VarDefinition"
        );
    }

    #[test]
    fn settings_includes_flattened_fields() {
        let generator = SchemaGenerator::new();
        let schema = generator.generate();

        // Settings uses #[serde(flatten)] on sub-structs.
        // schemars should include all flattened fields. Check for a few key ones
        // by looking at the full schema JSON.
        let schema_str = serde_json::to_string(&schema).unwrap();

        // These are fields from flattened sub-structs that should appear somewhere
        for field in &[
            "default_output",
            "parallel",
            "max_parallel",
            "logging",
            "log_retention_days",
            "secret_env",
            "default_environment",
        ] {
            assert!(
                schema_str.contains(field),
                "schema should contain flattened field: {field}"
            );
        }
    }

    #[test]
    fn check_enum_referenced() {
        let generator = SchemaGenerator::new();
        let schema = generator.generate();

        let schema_str = serde_json::to_string(&schema).unwrap();
        // The Check enum (tagged with type) should be referenced
        assert!(
            schema_str.contains("Check") || schema_str.contains("check"),
            "schema should reference Check type"
        );
    }

    #[test]
    fn schema_is_valid_json() {
        let generator = SchemaGenerator::new();
        let schema = generator.generate();

        // Should round-trip through JSON pretty-printing
        let pretty = serde_json::to_string_pretty(&schema).unwrap();
        let _: Value = serde_json::from_str(&pretty).unwrap();
    }

    #[test]
    fn default_impl_works() {
        let generator = SchemaGenerator;
        let schema = generator.generate();
        assert!(schema["properties"].is_object());
    }

    #[test]
    fn embedded_schema_is_valid_json() {
        let schema: Value = serde_json::from_str(EMBEDDED_SCHEMA_JSON).unwrap();
        assert_eq!(schema["$schema"], "http://json-schema.org/draft-07/schema#");
        assert_eq!(schema["type"], "object");
    }

    #[test]
    fn embedded_schema_matches_generated() {
        let generated = SchemaGenerator::new().generate();
        let embedded = embedded_schema();

        // Compare the canonical fields to detect drift.
        // If this fails, run: cargo run -- schema -o generated/schema.json
        assert_eq!(
            generated, embedded,
            "Embedded schema is stale. Regenerate with: cargo run -- schema -o generated/schema.json"
        );
    }
}
